apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KC_DB_URL_HOST: postgres
  DB_VENDOR: postgres
  DB_ADDR: postgres
  DB_DATABASE: keycloak
  KC_HOSTNAME: localhost
  KC_HOSTNAME_STRICT: 'false'
  KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
  KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key