- name: Adicionar repositório Helm do Rancher
  shell: |
    helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
    helm repo update
  args:
    executable: /bin/bash

- name: Criar namespace para o Rancher
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: cattle-system

- name: Instalar Cert-Manager
  shell: |
    kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml
    kubectl -n cert-manager rollout status deploy/cert-manager
    kubectl -n cert-manager rollout status deploy/cert-manager-webhook
    kubectl -n cert-manager rollout status deploy/cert-manager-cainjector
  args:
    executable: /bin/bash

- name: Criar Issuer para Cert-Manager
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Issuer
      metadata:
        name: rancher-issuer
        namespace: cattle-system
      spec:
        selfSigned: {}

- name: Criar Certificado TLS para Rancher
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: tls-rancher-ingress
        namespace: cattle-system
      spec:
        secretName: tls-rancher-ingress
        duration: 2160h # 90d
        renewBefore: 360h # 15d
        subject:
          organizations:
            - My Organization
        commonName: "{{ rancher_hostname }}"
        dnsNames:
          - "{{ rancher_hostname }}"
        issuerRef:
          name: rancher-issuer
          kind: Issuer

- name: Instalar Rancher com Helm
  shell: |
    helm install rancher rancher-latest/rancher \
      --namespace cattle-system \
      --set hostname={{ rancher_hostname }}
  args:
    executable: /bin/bash

- name: Criar Ingress para Rancher
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: rancher
        namespace: cattle-system
        annotations:
          nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
          nginx.ingress.kubernetes.io/rewrite-target: /$2
      spec:
        ingressClassName: nginx
        rules:
          - host: "{{ rancher_hostname }}"
            http:
              paths:
                - path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: rancher
                      port:
                        number: 80
        tls:
          - hosts:
              - "{{ rancher_hostname }}"
            secretName: tls-rancher-ingress

- name: Instalar o Nginx Ingress Controller usando o Helm
  shell: |
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    helm repo update
    helm install nginx-ingress ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace
  args:
    executable: /bin/bash

- name: Verificar se o Nginx Ingress Controller está em execução
  shell: kubectl get pods -n ingress-nginx
  register: ingress_nginx
  args:
    executable: /bin/bash

- name: Exibir saída do Nginx Ingress Controller 
  debug:
    msg: "{{ ingress_nginx.stdout }}"


- name: Verificar o Serviço do Nginx Ingress Controller
  shell: kubectl get svc -n ingress-nginx
  register: ingress_nginx_svc
  args:
    executable: /bin/bash

- name: Exibir saída do Serviço do Nginx Ingress Controller
  debug:
    msg: "{{ ingress_nginx_svc.stdout }} - OBS: Anote o EXTERNAL-IP, pois ele deve ser o IP para o qual seu DNS {{ rancher_hostname }} deve apontar."


- name: Verificar os Logs do Nginx Ingress Controller
  shell: kubectl logs -l app.kubernetes.io/name=ingress-nginx -n ingress-nginx
  register: ingress_nginx_log
  args:
    executable: /bin/bash

- name: Exibir saída do Nginx Ingress Controller Logs
  debug:
    msg: "{{ ingress_nginx_log.stdout }}"

- name: Verificar pods do Rancher
  shell: kubectl get pods -n cattle-system
  register: rancher_pods
  args:
    executable: /bin/bash

- name: Exibir saída dos pods do Rancher
  debug:
    msg: "{{ rancher_pods.stdout }}"

- name: Verificar logs do Nginx Ingress Controller
  shell: kubectl logs -l app.kubernetes.io/name=ingress-nginx -n ingress-nginx
  register: ingress_logs
  args:
    executable: /bin/bash

- name: Exibir logs do Nginx Ingress Controller
  debug:
    msg: "{{ ingress_logs.stdout }}"

- name: Verificar serviço Rancher
  shell: kubectl get svc -n cattle-system
  register: rancher_svc
  args:
    executable: /bin/bash

- name: Exibir serviço Rancher
  debug:
    msg: "{{ rancher_svc.stdout }}"

- name: Verificar certificado TLS do Rancher
  shell: kubectl describe certificate tls-rancher-ingress -n cattle-system
  register: tls_certificate
  args:
    executable: /bin/bash

- name: Exibir certificado TLS do Rancher
  debug:
    msg: "{{ tls_certificate.stdout }}"